---
language: python
cache:
  directories:
    - $HOME/.cache/pip
matrix:
  include:
    - python: 3.6
      env: TOXENV=docs
    - python: 3.6
      env: TOXENV=py36
install:
  - pip install tox
script:
  - tox
